services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: prod
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: prod