services:
  backend:
    container_name: backend 
    build: 
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    depends_on:
      - db  
    volumes:
      - ./backend:/app
      - /usr/app/node_modules
      - ./backend/nodemon.json:/app/nodemon.json
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:${SERVER_PORT:-3000}'
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:80'
    environment:
      - CHOKIDAR_USEPOLLING=true     