services:
  backend:
    container_name: backend 
    build: 
      context: ./backend
    depends_on:
      - db  
    volumes:
      - ./backend:/app
      - /usr/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:3000'
  db:
    container_name: db
    image: mongo
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:80'
    environment:
      - CHOKIDAR_USEPOLLING=true     